name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: install angular cli
      run: |
          npm install -g @angular/cli --latest
          ng config -g cli.warnings.versionMismatch false
    - name: Run ModelBuilderServerless tests
      run: dotnet test ModelBuilderServerless.Tests
    - name: Run website tests
      run: dotnet test Website.Tests
    - name: Publish website
      run: dotnet publish Website -r linux-x64 --self-contained true -o publish
    - name: Stop website
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_Host }}
        username: ${{ secrets.SSH_Username }}
        key: ${{ secrets.SSH_Key }}
        port: 22
        script: ./KillSite.sh
    - name: Deploy website via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_Host }}
        username: ${{ secrets.SSH_Username }}
        key: ${{ secrets.SSH_Key }}
        port: 22
        source: "publish/*"
        target: "Deployment"
        overwrite: true
    - name: Start website
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_Host }}
        username: ${{ secrets.SSH_Username }}
        key: ${{ secrets.SSH_Key }}
        port: 22
        script: ./CD.sh
